### ISSUE TITLE
Social media graphic for CoD Summit

### ISSUE THREAD

**Issue by it09** [bacalhau-project/devrel#1]
- [x] Call for Papers
- [x] call for attendees
- [x] talks promo

**Comment by yenyrubiano** [comment]
Graphics for Twitter were created and submitted. Attached is a zip file with all graphics.
I am working on graphics for LinkedIn to share next month.

[compute-over-data-twitter.zip](https://github.com/bacalhau-project/devrel/files/11032608/compute-over-data-twitter.zip)

**Comment by yenyrubiano** [comment]
@it09 please find attached the final social media graphics for Twitter. The only job title I am missing is Kai Davenport. I am waiting for his answer.

CC @fakela 

[compute-over-data-twitter.zip](https://github.com/bacalhau-project/devrel/files/11035495/compute-over-data-twitter.zip)

**Comment by yenyrubiano** [comment]
[compute-over-data-linkedin.zip](https://github.com/bacalhau-project/devrel/files/11042490/compute-over-data-linkedin.zip)
Attached are graphics for LinkedIn

**Comment by yenyrubiano** [comment]
Updated graphics attached:

![Image](https://user-images.githubusercontent.com/17787039/229588114-a6e9130f-f350-4044-a298-4c37a8bb44ba.png)
![Image](https://user-images.githubusercontent.com/17787039/229588115-064ef9be-4122-4782-b601-bf06579655bf.png)

**Comment by yenyrubiano** [comment]
![Image](https://user-images.githubusercontent.com/17787039/229589305-78c4489e-d4e4-43ae-86ee-5dea838edbeb.png)
![Image](https://user-images.githubusercontent.com/17787039/229589304-9cd00cdc-9571-4b2f-af14-183099a8bfc2.png)
