### ISSUE TITLE
Swag for CoD Summit: T-Shirts

### ISSUE THREAD

**Issue by it09** [bacalhau-project/devrel#3]
- [x] Design t-shirt
- [x] Design stickers
- [x] produce & ship to venue

**Comment by yenyrubiano** [comment]
@it09 attached are 2 ideas for the event t-shirt, please review:

[cod-tshirt-design-v1.zip](https://github.com/bacalhau-project/devrel/files/11113022/cod-tshirt-design-v1.zip)

**Comment by it09** [comment]
shall we do black t-shirts?

**Comment by yenyrubiano** [comment]
Note: Dividing this ticket to several tickets for each swag.

**Comment by yenyrubiano** [comment]
@it09 please review front:

![Image](https://user-images.githubusercontent.com/17787039/231506308-f664a286-da98-40e3-ab02-99c45fedb391.png)

**Comment by it09** [comment]
Shall wewrite CoD Summit^3?
Also shall we have one option without large codwg logo?

**Comment by yenyrubiano** [comment]
Idea #1:

![Image](https://user-images.githubusercontent.com/17787039/233695644-a1b40177-0dfb-48d8-b294-308b9f72698f.png)
![Image](https://user-images.githubusercontent.com/17787039/233695645-0ed404d2-0b67-46ff-9dde-ffea5b636f0b.png)

Idea #2:

![Image](https://user-images.githubusercontent.com/17787039/233695796-5125f9be-5fab-4874-86a2-e8a6ba736745.png)
![Image](https://user-images.githubusercontent.com/17787039/233695795-aa2880d0-46bb-4009-a57f-3d695ff78501.png)

**Comment by yenyrubiano** [comment]
@it09  please let me know the design you liked the best. Do you have a company already in mind to print them in the UK, or do you prefer to get them printed in the US?

**Comment by yenyrubiano** [comment]
@it09 changes have been completed. Please review:

![Image](https://user-images.githubusercontent.com/17787039/234404656-4a08ea57-d764-4d47-9c02-fa125510f3d9.png)

**Comment by it09** [comment]
This is great! Could you make font even smaller on back and front? Also could you move cod logo on the front near the logo and make it small and transparent

**Comment by yenyrubiano** [comment]
@it09 updated design attached.

![Image](https://user-images.githubusercontent.com/17787039/235163084-f649e83a-30b0-4626-a187-d78154887c9c.png)

**Comment by yenyrubiano** [comment]
Status: Waiting on quote

**Comment by yenyrubiano** [comment]
Status: Sent to print and paid.
