### ISSUE TITLE
website update

### ISSUE THREAD

**Issue by it09** [bacalhau-project/devrel#33]

**Comment by it09** [comment]
https://filecoinproject.slack.com/archives/C04EQ9GQDC1/p1679738742753169

**Comment by yenyrubiano** [comment]
@it09 https://www.bacalhau.org/ redesigns are ready for you to review here: https://www.figma.com/file/4ZOZGNnBOmwhkCZ1IcI5nM/Bacalhau-Main-Site?node-id=0%3A1&t=w0AwXpujbU1U2nY6-1

I have created 3 different versions: 
V1: Is more elaborated with more content (perfect for SEO) and marketing -as needed.
V2: Is just like the sample David sent over.
V3: Simple with more text for SEO purposes.

I look forward to receiving your feedback.

**Comment by yenyrubiano** [comment]
Status: Received comments. V3 was chosen with a few edits.

**Comment by fakela** [comment]
@yenyrubiano I can't access the file

**Comment by yenyrubiano** [comment]
Status: design V4 is approved and ready to be implemented.

**Comment by yenyrubiano** [comment]
Status: Site has been coded and pull request has been sent: https://github.com/bacalhau-project/website/pull/24
@it09

**Comment by yenyrubiano** [comment]
Status: Branch was merged to master, but Lindsay requested to revert the branch. There is a redirect issue with the site.
