### ISSUE TITLE
CoD Summit: schedule timetable for each track

### ISSUE THREAD

**Issue by it09** [bacalhau-project/devrel#37]

**Comment by wesfloyd** [comment]
We've added a draft schedule for the [Applications and Security track here](https://airtable.com/appn1cAuh9f9I0ru0/tblh0dMxhS2m8yx57/viwlejK7e2S8Das4N?blocks=hide). Let me know if you have any feedback

<img width="1111" alt="image" src="https://user-images.githubusercontent.com/260568/229504859-5ac7f6a4-5571-44f2-b559-49ce88b60ef7.png">
