### ISSUE TITLE
research related communitites at Boston to invite for codsummit

### ISSUE THREAD

**Issue by it09** [bacalhau-project/devrel#38]

**Comment by XandraMcC** [comment]
- DeSci Boston past speakers & attendees
- Sam Broner - Blockchain @ MIT https://twitter.com/SamBroner - https://sambroner.com/
- Weavechain
- MIT Slone Blockchain
- MIT Hacking Medicine

**Comment by XandraMcC** [comment]
Data Science for Social Good: This group is focused on using data science techniques to tackle social and environmental issues. While not specifically focused on open data, many of their projects involve using publicly available datasets to address pressing problems.
Website: https://www.dssg.io/

Harvard Open Data Project (HODP): Based at Harvard University, the HODP is a student-run organization that aims to promote open data, transparency, and civic engagement within the Harvard community and beyond.
Website: https://www.hodp.org/

MIT Media Lab: The MIT Media Lab, though not specifically an open data community, has several research groups that work on open data projects and related topics, such as digital currencies, human dynamics, and civic media.
Website: https://www.media.mit.edu/

**Comment by XandraMcC** [comment]
Emails sent to Sam Broner, HODP, Weavechain, BRAIN initiative

**Comment by XandraMcC** [comment]
Reached out to Boston DAO - they will cross promote
