### ISSUE TITLE
CoD Summit: create panels for each track

### ISSUE THREAD

**Issue by it09** [bacalhau-project/devrel#40]

**Comment by wesfloyd** [comment]
@it09 do you have an preference or recommendation on topics for our Application & Security panel? For now we've [added a placeholder](https://airtable.com/appn1cAuh9f9I0ru0/tblh0dMxhS2m8yx57/viwlejK7e2S8Das4N?blocks=hide) for "Panel Discussion: emerging use cases for Compute Over Data"

<img width="1352" alt="image" src="https://user-images.githubusercontent.com/260568/229504276-f6e9d8d0-250e-4f37-8591-0ad3540ea236.png">
