### ISSUE TITLE
Twitter: schedule bacalhau examples

### ISSUE THREAD

**Issue by it09** [bacalhau-project/devrel#44]
- [ ] all examples form this repo https://docs.bacalhau.org/examples/model-inference/
- [ ] cta github stars : https://github.com/bacalhau-project/bacalhau
- [ ] make sure timing is not the same as other tweets - they are spread out

**Comment by XandraMcC** [comment]
⚡️Experience lightning-fast video resizing with Bacalhau Sharding! Tap into the power of parallel processing for large-scale video file handling. Get started with our step-by-step tutorial: https://docs.bacalhau.org/examples/data-engineering/simple-parallel-workloads/ #ParallelComputing #VideoProcessing

🔗💥Supercharge your Ethereum blockchain analysis with Ethereum-ETL and Bacalhau! Skip the week-long node sync and dive into scalable, decentralized data processing. Learn how in our tutorial: https://docs.bacalhau.org/examples/data-engineering/blockchain-etl/ #BlockchainAnalysis #EthereumETL #Bacalhau

🎨Discover the power of Stable Diffusion on a GPU with Bacalhau! Turn text into stunning images using this open-source alternative to DALL·E 2. Dive into our tutorial and unleash your creativity: https://docs.bacalhau.org/examples/model-inference/stable-diffusion-gpu/ #StableDiffusion #Bacalhau #TextToImage

💻Harness the power of Stable Diffusion on a CPU with Bacalhau! Explore our step-by-step tutorial to develop and deploy amazing text-to-image transformations: https://docs.bacalhau.org/examples/model-inference/stable-diffusion-cpu/ #StableDiffusion #Bacalhau #CPU

🚀Finetune your Stable Diffusion model and run inference on Bacalhau. Learn how to convert your model weights to ckpt and start generating images from text: https://docs.bacalhau.org/examples/model-inference/Stable-Diffusion-CKPT-Inference/ #StableDiffusion #Bacalhau #Inference

🕵️‍♀️Detect objects in real-time with YOLOv5 on Bacalhau! Check out our tutorial to perform end-to-end object detection using the Ultralytics YOLOv5 Docker Image: https://docs.bacalhau.org/examples/model-inference/object-detection-yolo5/ #YOLOv5 #Bacalhau #ObjectDetection

**Comment by XandraMcC** [comment]
Example tweets scheduled for:
3:00 PM · Thu 30 March 2023
4:00 PM · Mon 3 April 2023
4:15 PM · Wed 5 April 2023
2:00 PM · Fri 7 April 2023
5:15 PM · Mon 10 April 2023
6:00 PM · Wed 12 April 2023
3:15 PM · Mon 8 May 2023
