### ISSUE TITLE
Linkedin socials

### ISSUE THREAD

**Issue by it09** [bacalhau-project/devrel#46]
- [ ] graphics from here https://github.com/bacalhau-project/devrel/issues/1
- [ ] check with @it09 on messaging draft

**Comment by XandraMcC** [comment]
🌱Spring is here, and so is Bacalhau [v0.3.25](https://github.com/bacalhau-project/bacalhau/releases/tag/v0.3.25)! We've integrated [Bacalhau](https://github.com/bacalhau-project/bacalhau) with Airflow, added job cancellation, removed sharding, and introduced multi-arch support. Also, we're excited about our ethical AI art project [Waterlily](https://www.waterlily.ai/) (watch a demo [here](https://www.youtube.com/watch?v=mMS6ww64mBM)) & partnership with [Filecoin Green](https://green.filecoin.io/). You can get more details on what the team is working on every month in our[ project report](https://bacalhau.substack.com/s/project-report?utm_source=substack&utm_medium=menu).

🗓️Mark your calendars for the CoD Summit^3 in Boston on May 9-10! Join us for an unforgettable event packed with cutting-edge insights, groundbreaking ideas, and top-notch networking opportunities. Register now and explore speaking and sponsorship opportunities! 🚀
🔗 More info: [codsummit.io](https://www.codsummit.io/)

**Comment by XandraMcC** [comment]
Sent to Sara Hamdan - PLN Updates is scheduled for April 11 - https://filecoinproject.slack.com/archives/C018EJ8LWH1/p1680089358804669
