### ISSUE TITLE
cod summit: reach out to newsletters

### ISSUE THREAD

**Issue by it09** [bacalhau-project/devrel#48]
Reach out to Newsletters about attending/sponsoring cod summit - 
- [ ] Emily - check with her who else is doing - i think she mentioned Dame
- [ ] Dame?
- [ ] messaging draft
- [ ] check with @it09 the messaging draft

**Comment by XandraMcC** [comment]
Reached out to Emily - she directed me to Rich Chang. Messaged him. Waiting to hear back.

**Comment by XandraMcC** [comment]
PLN Updates run by Sara Hamdan

**Comment by XandraMcC** [comment]
Sent to Sara Hamdan - PLN Updates is scheduled for April 11 - https://filecoinproject.slack.com/archives/C018EJ8LWH1/p1680089358804669

(Duplicated by #46 )
