### ISSUE TITLE
Web2 hackathons

### ISSUE THREAD

**Issue by it09** [bacalhau-project/devrel#50]
- [ ] research relevant hackathons for Bacalhau
-  data
-  iot
-  cloud
-  distributed

**Comment by XandraMcC** [comment]
https://www.notion.so/ab7bd62497e5423c83e935d9e7594444?v=1580145058fc4646a833393b8f5201bd

**Comment by XandraMcC** [comment]
- [ ] Recommend ETHGlobal Paris OR ETHGlobal Waterloo (within a month of each other) – I recommend ETH Paris as it coincides with ETH CC. Also, there is Hack the North in Waterloo in late summer which would be very appropriate.
- [ ] Will email HTN (sponsor@hackthenorth.com) and ask about 2023 dates
- [ ] Will email HackZurich (info@hackzurich.com) - seems to be a lot of big industry partners. Will ask how Bac can fit into the hack
- [ ] ETH Global NY will be good to get US exposure (recommend over Instanbul)
- [ ] Highly recommend EU Datathon (date TBA - 2022 was in October) https://op.europa.eu/en/web/eudatathon
- [ ] ETH Global Online is recommended as it is a long timeline & highly accessible
- [ ] Recommend looking at Hack MIT (Date TBA - Q4 hackathon), a more general hack - email team@hackmit.org for more info 
- [ ] Datathon.cat is a good, data-focused hack (MLH hack). Date TBA (Q4). Email datathon.fme@upc.edu for more info
- [ ] Durhack in Durham, UK. General hack with good sponsors. Data TBA (Q4). Email hello@durhack.com for more info

All info here: https://www.notion.so/pl-strflt/d976cbded30e49d4871d9532743ca807?v=5bd84cd7aab0495e8c56aff6d57ae1c1

**Comment by XandraMcC** [comment]
DRAFT EMAIL @it09 

Subject: Inquiry about [HACKATHON NAME] Hackathon 2023 & Sponsorship Opportunities for Bacalhau Project

Dear [Hackathon Organizer's Name],

My name is [Name of Sender] and I am part of the team at [Bacalhau Project](https://github.com/bacalhau-project/bacalhau), a cutting-edge platform focused on fast, cost-efficient, and secure computation by running jobs where the data is generated and stored. Our platform allows users to streamline their existing workflows without the need for extensive rewriting by running arbitrary Docker containers and WebAssembly (wasm) images as tasks.

The [NAME OF HACKATHON] Hackathon that you are organizing this year sounds like it could be a great fit for us, and I am writing to inquire about further details of the event, as well as any sponsorship opportunities that might be available for Bacalhau. We are keen on supporting the tech community and believe that the hackathon would provide an excellent opportunity for us to engage with talented developers, introduce our platform to a broader audience, and contribute to the growth of the industry.

Could you please provide more information about the hackathon, such as the event's main theme, target audience, expected number of participants, and any other relevant details? Additionally, we would appreciate it if you could share the various sponsorship packages and opportunities available, along with their respective benefits and costs.


Please feel free to reach out to me directly at [EMAIL] to discuss this further. Alternatively, you may provide us with the appropriate contact information.

Thank you for your time, and we look forward to learning more about the 2023 Hackathon and possible collaboration opportunities.

**Comment by XandraMcC** [comment]
@it09 – Is the above copy okay to send out?

**Comment by it09** [comment]
its good - but lets wait on the budget first - dont send it yet
