### ISSUE TITLE
CoD Summit announcement

### ISSUE THREAD

**Issue by it09** [bacalhau-project/devrel#56]
CTA 03/04/2023

- [ ] reach out to Yeny for diagrams/graphics
- [ ] update [notion page](https://www.notion.so/pl-strflt/Content-plan-0f0a480738ce494a9d0c97270799fe38) with the blog link

Subjects to cover in the blog:
 - definition of cod summit/things it covers compute over data, decentralized compute & ai https://www.codsummit.io/
 - organized by cod wg - ask wes for a definition, aims, north start, etc
 - prominent speakers - David, Brooklyn, a guy from fluence labs, peter wang
 - ask David if we can tease about bacalhau launch in this blog

**Comment by XandraMcC** [comment]
https://blog.bacalhau.org/publish/post/111853505
