### ISSUE TITLE
Update LaunchPad Presentation

### ISSUE THREAD

**Issue by yenyrubiano** [bacalhau-project/devrel#63]

**Comment by yenyrubiano** [comment]
Status: All visible slides have been updated. Illustrations/diagrams are left to do.

**Comment by yenyrubiano** [comment]
Status: Obtaining info about slides that are hidden.

**Comment by yenyrubiano** [comment]
@it09 Ready to be reviewed - only missing Architecture diagram.

**Comment by it09** [comment]
Perfect! all good! thank you!
