### ISSUE TITLE
Design TShirts and Hoodies for Bacalhau

### ISSUE THREAD

**Issue by yenyrubiano** [bacalhau-project/devrel#64]

**Comment by yenyrubiano** [comment]
@it09 please find attached 3 different proposals for t-shirts.


![Image](https://user-images.githubusercontent.com/17787039/231025181-14811e16-ee46-4ebd-a8b6-ecf1dd13195c.jpg)
![Image](https://user-images.githubusercontent.com/17787039/231025183-637f57b5-a36b-44bc-bc58-1ff6b921ace7.jpg)
![Image](https://user-images.githubusercontent.com/17787039/231025182-5fc9f1b3-98a1-4b69-91a7-e8ccff4568c6.jpg)

**Comment by yenyrubiano** [comment]
@it09 please review these new proposals based on your latest feedback:


![Image](https://user-images.githubusercontent.com/17787039/233520500-95af970d-2ce3-4730-9759-d150d677a056.png)



![Image](https://user-images.githubusercontent.com/17787039/233520506-c23922c5-09fa-48a6-98fa-51f9acb60211.png)



![Image](https://user-images.githubusercontent.com/17787039/233520516-9de8df3e-f924-42e9-b1ff-5f8529ae82cd.png)

**Comment by it09** [comment]
it looks good

**Comment by yenyrubiano** [comment]
@it09 please let me know the design you liked the best. Do you have a company already in mind to print them in the UK, or do you prefer to get them printed in the US?

**Comment by it09** [comment]
<img width="660" alt="Screenshot 2023-04-25 at 10 10 41" src="https://user-images.githubusercontent.com/109608468/234230278-64ecdba7-0234-4626-8608-aa844abf4385.png">
the last one is great!

**Comment by yenyrubiano** [comment]
Final t-shirt design attached:

![Image](https://user-images.githubusercontent.com/17787039/234401904-45c4295f-bd08-408f-8774-acd4987aaf79.png)

**Comment by yenyrubiano** [comment]
Status: Waiting on quote.

**Comment by yenyrubiano** [comment]
Status: Sent to print and paid.
