### ISSUE TITLE
COD Summit^3 - Branding on social events

### ISSUE THREAD

**Issue by XandraMcC** [bacalhau-project/devrel#75]

**Comment by yenyrubiano** [comment]
@it09 could you please provide more details here.

**Comment by yenyrubiano** [comment]
Status: obtaining clarification from Carolyn

**Comment by carolynjlee** [comment]
@XandraMcC what social events are we talking about? I'm just showing talks [per the schedule for Day 1 and 2](https://airtable.com/appn1cAuh9f9I0ru0/tblh0dMxhS2m8yx57/viwQNEXfpcuJtTAQ8?blocks=hide). Thanks!
