### ISSUE TITLE
COD Summit^3 - Set up sponsors Expo booth

### ISSUE THREAD

**Issue by XandraMcC** [bacalhau-project/devrel#76]
Fluence Labs - Silver

**Comment by yenyrubiano** [comment]
@it09 could you please provide more details here.

**Comment by yenyrubiano** [comment]
Status: obtaining clarification from Carolyn

**Comment by carolynjlee** [comment]
10x10 space for the 2 sponsors. Are there any else @XandraMcC? If you could change the status in Airtable to "[confirmed](https://airtable.com/appn1cAuh9f9I0ru0/tblUi5qnaFz7jJKlV/viw43j0GC44ogCFuV?blocks=hide)" that would be great.
<img width="393" alt="Screenshot 2023-04-27 at 7 01 42 AM" src="https://user-images.githubusercontent.com/94921021/234857249-50e72ea5-0a4e-4f84-9c46-f0e40ec8b698.png">

**Comment by carolynjlee** [comment]
Tables are 6' x 30" 😉 btw.

**Comment by XandraMcC** [comment]
@carolynjlee - thank you! Are there electric & monitors available if sponsors want them?

**Comment by carolynjlee** [comment]
@XandraMcC yes it's possible but for a cost (which doesn't look like there is a budget for it).

**Comment by yenyrubiano** [comment]
@carolynjlee any designs needed on my end for this?

**Comment by carolynjlee** [comment]
@yenyrubiano no I believe the sponsors will be bringing their setup in so we should be good ;-)
