### ISSUE TITLE
track leads: build initial pipeline

### ISSUE THREAD

**Issue by it09** [bacalhau-project/devrel#8]
- [ ] Reach out to anyone who you accepted for your track - that way, they can start preparing for the conference
 - [ ] find speakers
 - [ ] start thinking who else is good for your track
 - [ ] https://airtable.com/appn1cAuh9f9I0ru0/tblh0dMxhS2m8yx57/viw7SK6wiTjpyjTJL?blocks=hide

**Comment by wesfloyd** [comment]
For the item regarding "Reach out to anyone who you accepted for your track" - are there specific logistics items we can share with them: how much time they have to present, which day/time they will present?

Could we start a Slack channel to ask presenters to join for the latest logistics information? Or should we communicate with them via email?
