### ISSUE TITLE
Swag for CoD Summit: Stickers

### ISSUE THREAD

**Issue by yenyrubiano** [bacalhau-project/devrel#99]

**Comment by yenyrubiano** [comment]
@it09 please review laptop sticker designs:

![Image](https://user-images.githubusercontent.com/17787039/232124090-1daf4584-0f9f-4590-ab29-1a8d6653f3f7.jpg)

**Comment by it09** [comment]
the one with qr code - could we focus on this only? could we instead of github logo out bacalhau logo and say Bacalhau?

**Comment by it09** [comment]
lets have icons of cod summit and link to cod.cloud instead of bacalhau - bacalhau should go downstars together with the sponsors @yenyrubiano

**Comment by yenyrubiano** [comment]
@it09 please find attached the updated sticker sheet. Please note that the colors look different because it is already saved for printing.

![Image](https://user-images.githubusercontent.com/17787039/234114195-aad7cd9c-bd47-4895-9634-2017cd94063b.jpg)

**Comment by it09** [comment]
This is awesome! Could you please make top right?

**Comment by yenyrubiano** [comment]
Status: Finding printing options.

**Comment by yenyrubiano** [comment]
Status: Submitted stickers for print and submitted an access to Iryna for delivery and payment. Final file is attached.


[bacalhau stickers FINAL CMYK 2.pdf](https://github.com/bacalhau-project/devrel/files/11334962/bacalhau.stickers.FINAL.CMYK.2.pdf)
